// Code generated by protoc-gen-go.
// source: pbproject.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	pbproject.proto

It has these top-level messages:
	PbProject
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PbProject struct {
	Id       int32                 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name     string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Uri      string                `protobuf:"bytes,3,opt,name=uri" json:"uri,omitempty"`
	Branches []*PbProject_PbBranch `protobuf:"bytes,4,rep,name=branches" json:"branches,omitempty"`
}

func (m *PbProject) Reset()                    { *m = PbProject{} }
func (m *PbProject) String() string            { return proto.CompactTextString(m) }
func (*PbProject) ProtoMessage()               {}
func (*PbProject) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PbProject) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PbProject) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PbProject) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *PbProject) GetBranches() []*PbProject_PbBranch {
	if m != nil {
		return m.Branches
	}
	return nil
}

type PbProject_PbBranch struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *PbProject_PbBranch) Reset()                    { *m = PbProject_PbBranch{} }
func (m *PbProject_PbBranch) String() string            { return proto.CompactTextString(m) }
func (*PbProject_PbBranch) ProtoMessage()               {}
func (*PbProject_PbBranch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *PbProject_PbBranch) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*PbProject)(nil), "main.PbProject")
	proto.RegisterType((*PbProject_PbBranch)(nil), "main.PbProject.PbBranch")
}

func init() { proto.RegisterFile("pbproject.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x48, 0x2a, 0x28,
	0xca, 0xcf, 0x4a, 0x4d, 0x2e, 0xd1, 0x03, 0xd2, 0x25, 0xf9, 0x42, 0x2c, 0xb9, 0x89, 0x99, 0x79,
	0x4a, 0xd3, 0x19, 0xb9, 0x38, 0x03, 0x92, 0x02, 0x20, 0x32, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29,
	0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x40, 0x96, 0x90, 0x10, 0x17, 0x4b, 0x5e, 0x62, 0x6e,
	0xaa, 0x04, 0x13, 0x50, 0x84, 0x33, 0x08, 0xcc, 0x16, 0x12, 0xe0, 0x62, 0x2e, 0x2d, 0xca, 0x94,
	0x60, 0x06, 0x0b, 0x81, 0x98, 0x42, 0x26, 0x5c, 0x1c, 0x49, 0x45, 0x89, 0x79, 0xc9, 0x19, 0xa9,
	0xc5, 0x12, 0x2c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0x12, 0x7a, 0x20, 0xc3, 0xf5, 0xe0, 0x06, 0x03,
	0x59, 0x4e, 0x60, 0x15, 0x41, 0x70, 0x95, 0x52, 0x72, 0x5c, 0x1c, 0x30, 0x51, 0xb8, 0x3d, 0x8c,
	0x08, 0x7b, 0x92, 0xd8, 0xc0, 0xce, 0x34, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xe4, 0x6d, 0x1e,
	0xe3, 0xb9, 0x00, 0x00, 0x00,
}
