// Code generated by protoc-gen-go.
// source: project.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	project.proto

It has these top-level messages:
	Project
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Project struct {
	Id       int32             `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name     string            `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Uri      string            `protobuf:"bytes,3,opt,name=uri" json:"uri,omitempty"`
	Branches []*Project_Branch `protobuf:"bytes,4,rep,name=branches" json:"branches,omitempty"`
}

func (m *Project) Reset()                    { *m = Project{} }
func (m *Project) String() string            { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()               {}
func (*Project) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Project) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Project) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *Project) GetBranches() []*Project_Branch {
	if m != nil {
		return m.Branches
	}
	return nil
}

type Project_Branch struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Project_Branch) Reset()                    { *m = Project_Branch{} }
func (m *Project_Branch) String() string            { return proto.CompactTextString(m) }
func (*Project_Branch) ProtoMessage()               {}
func (*Project_Branch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Project_Branch) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Project)(nil), "pb.Project")
	proto.RegisterType((*Project_Branch)(nil), "pb.Project.Branch")
}

func init() { proto.RegisterFile("project.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x28, 0xca, 0xcf,
	0x4a, 0x4d, 0x2e, 0xd1, 0x03, 0xd2, 0x25, 0xf9, 0x42, 0x4c, 0x05, 0x49, 0x4a, 0xbd, 0x8c, 0x5c,
	0xec, 0x01, 0x10, 0x51, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xd6,
	0x20, 0x20, 0x4b, 0x48, 0x88, 0x8b, 0x25, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x09, 0x28, 0xc2, 0x19,
	0x04, 0x66, 0x0b, 0x09, 0x70, 0x31, 0x97, 0x16, 0x65, 0x4a, 0x30, 0x83, 0x85, 0x40, 0x4c, 0x21,
	0x3d, 0x2e, 0x8e, 0xa4, 0xa2, 0xc4, 0xbc, 0xe4, 0x8c, 0xd4, 0x62, 0x09, 0x16, 0x05, 0x66, 0x0d,
	0x6e, 0x23, 0x21, 0xbd, 0x82, 0x24, 0x3d, 0xa8, 0xa1, 0x7a, 0x4e, 0x60, 0xb9, 0x20, 0xb8, 0x1a,
	0x29, 0x19, 0x2e, 0x36, 0x88, 0x18, 0xdc, 0x7c, 0x46, 0x84, 0xf9, 0x49, 0x6c, 0x60, 0xa7, 0x19,
	0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x1b, 0x17, 0x85, 0xff, 0xab, 0x00, 0x00, 0x00,
}
